'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Agent
    Public Property AgentId As Integer
    Public Property PortalName As String
    Public Property DisplayName As String
    Public Property Company As String
    Public Property Phone As String
    Public Property Fax As String
    Public Property Email As String
    Public Property Description As String
    Public Property Photo As Byte()

End Class
