'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property EmployeeID As Integer
    Public Property EmployeeNo As String
    Public Property Name As String
    Public Property Position As String
    Public Property Department As String
    Public Property Extension As String
    Public Property Email As String
    Public Property Password As String
    Public Property ReportTo As Nullable(Of Integer)
    Public Property Description As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property Active As Nullable(Of Boolean)
    Public Property CellPhone As String
    Public Property EmployeeSince As Nullable(Of Date)
    Public Property Picture As String

End Class
