'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GroupType
    Public Property Id As Integer
    Public Property ParentId As Nullable(Of Integer)
    Public Property GroupName As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String

End Class
