'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PropertyBaseInfo
    Public Property BBLE As String
    Public Property Number As String
    Public Property StreetName As String
    Public Property City As String
    Public Property State As String
    Public Property Zipcode As String
    Public Property Block As String
    Public Property Lot As String
    Public Property BuildingType As String
    Public Property NumOfStories As Nullable(Of Integer)
    Public Property NumOfUnit As Nullable(Of Integer)
    Public Property Accessibility As String
    Public Property TaxClass As String
    Public Property NumOfFamilies As Nullable(Of Integer)
    Public Property CO As Nullable(Of Boolean)
    Public Property FHA As Nullable(Of Boolean)
    Public Property FannieMae As Nullable(Of Boolean)
    Public Property FreddieMac As Nullable(Of Boolean)
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property UpdateDate As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property Borough As String
    Public Property AptNo As String
    Public Property COClass As String

End Class
