'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PropertyMortgage
    Public Property MortgageId As Integer
    Public Property CaseId As Integer
    Public Property Lender As String
    Public Property Loan As String
    Public Property LoanAmount As Nullable(Of Decimal)
    Public Property AuthorizationSent As String
    Public Property LienPosition As String
    Public Property Processor As Nullable(Of Integer)
    Public Property Negotiator As Nullable(Of Integer)
    Public Property Closer As Nullable(Of Integer)
    Public Property DateAssigned As Nullable(Of Date)
    Public Property Supervisor As Nullable(Of Integer)
    Public Property Status As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property UpdateDate As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property ShortSaleDept As Nullable(Of Integer)
    Public Property Fannie As Nullable(Of Boolean)
    Public Property FHA As Nullable(Of Boolean)
    Public Property Freddie As Nullable(Of Boolean)

End Class
