'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PropertyFloor
    Public Property BBLE As String
    Public Property FloorId As Integer
    Public Property Bedroom As Nullable(Of Integer)
    Public Property Bathroom As Nullable(Of Integer)
    Public Property Livingroom As Nullable(Of Integer)
    Public Property Kitchen As Nullable(Of Integer)
    Public Property Diningroom As Nullable(Of Integer)
    Public Property Occupied As String
    Public Property Lease As String
    Public Property Rent As String
    Public Property Type As String
    Public Property BoilerRoom As Nullable(Of Integer)
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property Access As String
    Public Property LockBox As String
    Public Property LockupDate As Nullable(Of Date)
    Public Property LockedBy As String
    Public Property LastChecked As Nullable(Of Date)

End Class
