'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SendMailPage

    '''<summary>
    '''EmailToIDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailToIDs As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''EmailCCIDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailCCIDs As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''EmailSuject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailSuject As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''EmailAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailAttachments As Global.DevExpress.Web.ASPxEditors.ASPxTextBox
End Class
