'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuctionPropertyView
    Public Property AuctionId As Integer
    Public Property BBLE As String
    Public Property DOBViolation As Nullable(Of Decimal)
    Public Property TaxesAmt As Nullable(Of Decimal)
    Public Property WaterAmt As Nullable(Of Decimal)
    Public Property EmployeeName As String
    Public Property BBL As String
    Public Property Address As String
    Public Property Zipcode As String
    Public Property Neighborhood As String
    Public Property BuildingClass As String
    Public Property AuctionDate As Nullable(Of Date)
    Public Property DateEntered As Nullable(Of Date)
    Public Property Lien As Nullable(Of Decimal)
    Public Property Judgment As Nullable(Of Date)
    Public Property Plaintiff As String
    Public Property Defendant As String
    Public Property IndexNo As String
    Public Property Referee As String
    Public Property AuctionLocation As String
    Public Property PlaintiffAttorney As String
    Public Property AttorneyPhone As String
    Public Property ForeclosureType As String
    Public Property AgentAssigned As String
    Public Property Grade As String
    Public Property PreviousAuctionDate As Nullable(Of Date)
    Public Property DeedRecorded As Nullable(Of Date)
    Public Property MaxAuctionBid As Nullable(Of Decimal)
    Public Property RenovatedValue As Nullable(Of Decimal)
    Public Property Points As String
    Public Property LeadType As String
    Public Property Description As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property C1stMotgrAmt As Nullable(Of Decimal)
    Public Property C2ndMotgrAmt As Nullable(Of Decimal)
    Public Property C3rdMortgrAmt As Nullable(Of Decimal)
    Public Property EmployeeID As Nullable(Of Integer)
    Public Property TeamName As String

End Class
