'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuditLog
    Public Property AuditId As Integer
    Public Property UserName As String
    Public Property EventDate As Date
    Public Property EventType As Integer
    Public Property TableName As String
    Public Property RecordId As String
    Public Property ColumnName As String
    Public Property OriginalValue As String
    Public Property NewValue As String
    Public Property CustomType As String
End Class
