'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BusinessCheck
    Public Property CheckId As Integer
    Public Property RequestId As Nullable(Of Integer)
    Public Property PaybleTo As String
    Public Property Amount As Decimal
    Public Property [Date] As Date
    Public Property CheckFor As String
    Public Property Description As String
    Public Property CreateBy As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property UpdateDate As Nullable(Of Date)
    Public Property Status As Nullable(Of Integer)

End Class
