'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CheckRequest
    Public Property RequestId As Integer
    Public Property Type As String
    Public Property BBLE As String
    Public Property CheckAmount As Nullable(Of Integer)
    Public Property TotalAmount As Nullable(Of Decimal)
    Public Property Description As String
    Public Property UpdateBy As String
    Public Property UpdateDate As Nullable(Of Date)
    Public Property RequestBy As String
    Public Property RequestDate As Nullable(Of Date)

End Class
