'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports IntranetPortal.Data

Partial Public Class DataStatu
    Public Property Category As String
    Public Property Status As Integer
    Public Property Name As String
    Public Property DisplayOrder As Nullable(Of Integer)
    Public Property Active As Nullable(Of Boolean)
    Public Property Description As String

    Public Shared Function LoadAllDataStatus() As List(Of DataStatu)
        Throw New NotImplementedException()
    End Function
End Class
