'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DialerContact
    Public Property inin_outbound_id As String
    Public Property ContactListId As String
    Public Property BBLE As String
    Public Property Agent As String
    Public Property PropertyAddress As String
    Public Property Owner As String
    Public Property CoOwner As String
    Public Property C1stMotgrAmt As Nullable(Of Decimal)
    Public Property C2ndMotgrAmt As Nullable(Of Decimal)
    Public Property DOBViolationsAmt As Nullable(Of Decimal)
    Public Property WaterAmt As Nullable(Of Decimal)
    Public Property TaxesAmt As Nullable(Of Decimal)
    Public Property Comments As String
    Public Property LeadsStatus As Nullable(Of Integer)
    Public Property Status As Nullable(Of Integer)
    Public Property LastUpdate As Nullable(Of Date)
    Public Property OwnerPhone1 As String
    Public Property CoOwnerPhone1 As String
    Public Property OwnerPhone2 As String
    Public Property CoOwnerPhone2 As String
    Public Property OwnerPhone3 As String
    Public Property CoOwnerPhone3 As String
    Public Property OwnerPhone4 As String
    Public Property CoOwnerPhone4 As String
    Public Property OwnerPhone5 As String
    Public Property CoOwnerPhone5 As String
    Public Property OwnerPhone6 As String
    Public Property CoOwnerPhone6 As String
    Public Property OwnerPhone7 As String
    Public Property CoOwnerPhone7 As String
    Public Property OwnerPhone8 As String
    Public Property CoOwnerPhone8 As String
    Public Property OwnerPhone9 As String
    Public Property CoOwnerPhone9 As String
    Public Property OwnerPhone10 As String
    Public Property CoOwnerPhone10 As String
    Public Property OwnerPhone11 As String
    Public Property CoOwnerPhone11 As String
    Public Property OwnerPhone12 As String
    Public Property CoOwnerPhone12 As String
    Public Property OwnerPhone13 As String
    Public Property CoOwnerPhone13 As String
    Public Property OwnerPhone14 As String
    Public Property CoOwnerPhone14 As String
    Public Property OwnerPhone15 As String
    Public Property CoOwnerPhone15 As String
    Public Property OwnerPhone16 As String
    Public Property CoOwnerPhone16 As String
    Public Property OwnerPhone17 As String
    Public Property CoOwnerPhone17 As String
    Public Property OwnerPhone18 As String
    Public Property CoOwnerPhone18 As String
    Public Property OwnerPhone19 As String
    Public Property CoOwnerPhone19 As String
    Public Property OwnerPhone20 As String
    Public Property CoOwnerPhone20 As String
    Public Property ContactCallable As String
    Public Property CallRecordLastAttempt_OwnerPhone1 As String
    Public Property CallRecordLastResult_OwnerPhone1 As String
    Public Property Callable_OwnerPhone1 As String
    Public Property CallRecordLastAttempt_OwnerPhone2 As String
    Public Property CallRecordLastResult_OwnerPhone2 As String
    Public Property Callable_OwnerPhone2 As String
    Public Property CallRecordLastAttempt_OwnerPhone3 As String
    Public Property CallRecordLastResult_OwnerPhone3 As String
    Public Property Callable_OwnerPhone3 As String
    Public Property CallRecordLastAttempt_OwnerPhone4 As String
    Public Property CallRecordLastResult_OwnerPhone4 As String
    Public Property Callable_OwnerPhone4 As String
    Public Property CallRecordLastAttempt_OwnerPhone5 As String
    Public Property CallRecordLastResult_OwnerPhone5 As String
    Public Property Callable_OwnerPhone5 As String
    Public Property CallRecordLastAttempt_OwnerPhone6 As String
    Public Property CallRecordLastResult_OwnerPhone6 As String
    Public Property Callable_OwnerPhone6 As String
    Public Property CallRecordLastAttempt_OwnerPhone7 As String
    Public Property CallRecordLastResult_OwnerPhone7 As String
    Public Property Callable_OwnerPhone7 As String
    Public Property CallRecordLastAttempt_OwnerPhone8 As String
    Public Property CallRecordLastResult_OwnerPhone8 As String
    Public Property Callable_OwnerPhone8 As String
    Public Property CallRecordLastAttempt_OwnerPhone9 As String
    Public Property CallRecordLastResult_OwnerPhone9 As String
    Public Property Callable_OwnerPhone9 As String
    Public Property CallRecordLastAttempt_OwnerPhone10 As String
    Public Property CallRecordLastResult_OwnerPhone10 As String
    Public Property Callable_OwnerPhone10 As String
    Public Property CallRecordLastAttempt_OwnerPhone11 As String
    Public Property CallRecordLastResult_OwnerPhone11 As String
    Public Property Callable_OwnerPhone11 As String
    Public Property CallRecordLastAttempt_OwnerPhone12 As String
    Public Property CallRecordLastResult_OwnerPhone12 As String
    Public Property Callable_OwnerPhone12 As String
    Public Property CallRecordLastAttempt_OwnerPhone13 As String
    Public Property CallRecordLastResult_OwnerPhone13 As String
    Public Property Callable_OwnerPhone13 As String
    Public Property CallRecordLastAttempt_OwnerPhone14 As String
    Public Property CallRecordLastResult_OwnerPhone14 As String
    Public Property Callable_OwnerPhone14 As String
    Public Property CallRecordLastAttempt_OwnerPhone15 As String
    Public Property CallRecordLastResult_OwnerPhone15 As String
    Public Property Callable_OwnerPhone15 As String
    Public Property CallRecordLastAttempt_OwnerPhone16 As String
    Public Property CallRecordLastResult_OwnerPhone16 As String
    Public Property Callable_OwnerPhone16 As String
    Public Property CallRecordLastAttempt_OwnerPhone17 As String
    Public Property CallRecordLastResult_OwnerPhone17 As String
    Public Property Callable_OwnerPhone17 As String
    Public Property CallRecordLastAttempt_OwnerPhone18 As String
    Public Property CallRecordLastResult_OwnerPhone18 As String
    Public Property Callable_OwnerPhone18 As String
    Public Property CallRecordLastAttempt_OwnerPhone19 As String
    Public Property CallRecordLastResult_OwnerPhone19 As String
    Public Property Callable_OwnerPhone19 As String
    Public Property CallRecordLastAttempt_OwnerPhone20 As String
    Public Property CallRecordLastResult_OwnerPhone20 As String
    Public Property Callable_OwnerPhone20 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone1 As String
    Public Property CallRecordLastResult_CoOwnerPhone1 As String
    Public Property Callable_CoOwnerPhone1 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone2 As String
    Public Property CallRecordLastResult_CoOwnerPhone2 As String
    Public Property Callable_CoOwnerPhone2 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone3 As String
    Public Property CallRecordLastResult_CoOwnerPhone3 As String
    Public Property Callable_CoOwnerPhone3 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone4 As String
    Public Property CallRecordLastResult_CoOwnerPhone4 As String
    Public Property Callable_CoOwnerPhone4 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone5 As String
    Public Property CallRecordLastResult_CoOwnerPhone5 As String
    Public Property Callable_CoOwnerPhone5 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone6 As String
    Public Property CallRecordLastResult_CoOwnerPhone6 As String
    Public Property Callable_CoOwnerPhone6 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone7 As String
    Public Property CallRecordLastResult_CoOwnerPhone7 As String
    Public Property Callable_CoOwnerPhone7 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone8 As String
    Public Property CallRecordLastResult_CoOwnerPhone8 As String
    Public Property Callable_CoOwnerPhone8 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone9 As String
    Public Property CallRecordLastResult_CoOwnerPhone9 As String
    Public Property Callable_CoOwnerPhone9 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone10 As String
    Public Property CallRecordLastResult_CoOwnerPhone10 As String
    Public Property Callable_CoOwnerPhone10 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone11 As String
    Public Property CallRecordLastResult_CoOwnerPhone11 As String
    Public Property Callable_CoOwnerPhone11 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone12 As String
    Public Property CallRecordLastResult_CoOwnerPhone12 As String
    Public Property Callable_CoOwnerPhone12 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone13 As String
    Public Property CallRecordLastResult_CoOwnerPhone13 As String
    Public Property Callable_CoOwnerPhone13 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone14 As String
    Public Property CallRecordLastResult_CoOwnerPhone14 As String
    Public Property Callable_CoOwnerPhone14 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone15 As String
    Public Property CallRecordLastResult_CoOwnerPhone15 As String
    Public Property Callable_CoOwnerPhone15 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone16 As String
    Public Property CallRecordLastResult_CoOwnerPhone16 As String
    Public Property Callable_CoOwnerPhone16 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone17 As String
    Public Property CallRecordLastResult_CoOwnerPhone17 As String
    Public Property Callable_CoOwnerPhone17 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone18 As String
    Public Property CallRecordLastResult_CoOwnerPhone18 As String
    Public Property Callable_CoOwnerPhone18 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone19 As String
    Public Property CallRecordLastResult_CoOwnerPhone19 As String
    Public Property Callable_CoOwnerPhone19 As String
    Public Property CallRecordLastAttempt_CoOwnerPhone20 As String
    Public Property CallRecordLastResult_CoOwnerPhone20 As String
    Public Property Callable_CoOwnerPhone20 As String

End Class
