'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GPAOffer
    Public Property Id As Integer
    Public Property BBLE As String
    Public Property OfferPrice As Nullable(Of Decimal)
    Public Property OfferId As Nullable(Of Integer)
    Public Property OfferFor As String
    Public Property GenerateBy As String
    Public Property Comments As String
    Public Property Description As String
    Public Property Status As Nullable(Of Integer)
    Public Property LastUpdate As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String

End Class
