'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PreSignRecord
    Public Property Id As Integer
    Public Property BBLE As String
    Public Property NeedSearch As Nullable(Of Boolean)
    Public Property SearchId As Nullable(Of Integer)
    Public Property ExpectedDate As Nullable(Of Date)
    Public Property NeedCheck As Nullable(Of Boolean)
    Public Property CheckRequestId As Nullable(Of Integer)
    Public Property DealAmount As Nullable(Of Decimal)
    Public Property PartiesCount As Nullable(Of Integer)
    Public Property Parties As String
    Public Property Description As String
    Public Property Status As String
    Public Property CreateBy As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property UpdateTime As Nullable(Of Date)

End Class
