'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PropertyNote
    Public Property Id As Integer
    Public Property BBLE As String
    Public Property BPOValue As Nullable(Of Decimal)
    Public Property FCStatus As String
    Public Property LastPaidInstallmentDt As Nullable(Of Date)
    Public Property NextPmtDueDt As Nullable(Of Date)
    Public Property FCStartDt As Nullable(Of Date)
    Public Property CurrentOccupancy As String
    Public Property DelinquentInterest As Nullable(Of Decimal)
    Public Property CurrentUPB As Nullable(Of Decimal)
    Public Property ForbearanceAmount As Nullable(Of Decimal)
    Public Property EscrowAdvanceBalance As Nullable(Of Decimal)
    Public Property Description As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property UpdateDate As Nullable(Of Date)
    Public Property UpdateBy As String

End Class
