
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class ShortSaleOffer

    Public Property OfferId As Integer

    Public Property BBLE As String

    Public Property OfferType As String

    Public Property DateOfContract As Nullable(Of Date)

    Public Property OfferAmount As Nullable(Of Decimal)

    Public Property DateSubmited As Nullable(Of Date)

    Public Property CreateDate As Nullable(Of Date)

    Public Property CreateBy As String

    Public Property BuyerEntity As String

    Public Property Signor As String

    Public Property DateCorpFormed As Nullable(Of Date)


End Class
