
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class ShortSaleCaseComment

    Public Property CommentId As Integer

    Public Property CaseId As Integer

    Public Property Comments As String

    Public Property OrderIndex As Nullable(Of Integer)

    Public Property CreateBy As String

    Public Property CreateDate As Nullable(Of Date)


End Class
