'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ShortSaleLeadsInfo
    Public Property BBLE As String
    Public Property IsLisPendens As Nullable(Of Boolean)
    Public Property IsOtherLiens As Nullable(Of Boolean)
    Public Property IsTaxesOwed As Nullable(Of Boolean)
    Public Property IsWaterOwed As Nullable(Of Boolean)
    Public Property IsECBViolations As Nullable(Of Boolean)
    Public Property IsDOBViolations As Nullable(Of Boolean)
    Public Property C1stMotgrAmt As Nullable(Of Decimal)
    Public Property C2ndMotgrAmt As Nullable(Of Decimal)
    Public Property C3rdMortgrAmt As Nullable(Of Decimal)
    Public Property TaxesAmt As Nullable(Of Decimal)
    Public Property TaxesOrderStatus As String
    Public Property TaxesOrderTime As Nullable(Of Date)
    Public Property TaxesOrderDeliveryTime As Nullable(Of Date)
    Public Property WaterAmt As Nullable(Of Decimal)
    Public Property WaterOrderStatus As String
    Public Property WaterOrderTime As Nullable(Of Date)
    Public Property WaterOrderDeliveryTime As Nullable(Of Date)
    Public Property ECBViolationsAmt As Nullable(Of Decimal)
    Public Property ECBOrderStatus As String
    Public Property ECBOrderTime As Nullable(Of Date)
    Public Property ECBOrderDeliveryTime As Nullable(Of Date)
    Public Property DOBViolationsAmt As Nullable(Of Decimal)
    Public Property DOBOrderStatus As String
    Public Property DOBOrderTime As Nullable(Of Date)
    Public Property DOBOrderDeliveryTime As Nullable(Of Date)
    Public Property AcrisOrderStatus As String
    Public Property AcrisOrderTime As Nullable(Of Date)
    Public Property AcrisOrderDeliveryTime As Nullable(Of Date)
    Public Property LastPaid As Nullable(Of Date)
    Public Property IsCoOnFile As Nullable(Of Boolean)
    Public Property TypeOfCo As String
    Public Property Owner As String
    Public Property CoOwner As String
    Public Property [Date] As Nullable(Of Date)
    Public Property PropertyAddress As String
    Public Property SaleDate As Nullable(Of Date)
    Public Property PropertyClass As String
    Public Property TaxClass As String
    Public Property SaleType As String
    Public Property Condition As String
    Public Property Block As String
    Public Property Lot As String
    Public Property DOBViolation As String
    Public Property Remark1 As String
    Public Property Remark2 As String
    Public Property Remark3 As String
    Public Property Remark4 As String
    Public Property Deed As String
    Public Property LPindex As String
    Public Property YearBuilt As String
    Public Property NumFloors As Nullable(Of Integer)
    Public Property BuildingDem As String
    Public Property LotDem As String
    Public Property EstValue As Nullable(Of Decimal)
    Public Property Number As String
    Public Property StreetName As String
    Public Property NeighName As String
    Public Property State As String
    Public Property ZipCode As String
    Public Property Borough As String
    Public Property Zoning As String
    Public Property MaxFar As String
    Public Property ActualFar As String
    Public Property NYCSqft As Nullable(Of Double)
    Public Property UnbuiltSqft As Nullable(Of Double)
    Public Property BuildingBBLE As String
    Public Property UnitNum As String
    Public Property Type As Nullable(Of Integer)
    Public Property Latitude As Nullable(Of Double)
    Public Property Longitude As Nullable(Of Double)
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property LastUpdate As Nullable(Of Date)
    Public Property UpdateBy As String

End Class
