'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ShortSaleActivityLog
    Public Property LogId As Integer
    Public Property BBLE As String
    Public Property ActivityDate As Nullable(Of Date)
    Public Property Source As String
    Public Property ActivityType As String
    Public Property ActivityTitle As String
    Public Property Description As String
    Public Property [Shared] As String
    Public Property AppId As Integer

End Class
