
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class SSLead

    Public Property BBLE As String

    Public Property LeadsName As String

    Public Property EmployeeID As Nullable(Of Integer)

    Public Property EmployeeName As String

    Public Property Process As Nullable(Of Integer)

    Public Property Status As Nullable(Of Integer)

    Public Property SubStatus As Nullable(Of Integer)

    Public Property CallbackDate As Nullable(Of Date)

    Public Property Neighborhood As String

    Public Property DeadReason As Nullable(Of Integer)

    Public Property Description As String

    Public Property LastUpdate As Nullable(Of Date)

    Public Property UpdateBy As String

    Public Property AssignDate As Nullable(Of Date)

    Public Property AssignBy As String

    Public Property MarkColor As Nullable(Of Integer)

    Public Property AppId As Nullable(Of Integer)


End Class
