
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TitleJudgementSearch

    Public Property JudgementId As Integer

    Public Property CaseId As Integer

    Public Property RepairTax As String

    Public Property RepairTaxDate As Nullable(Of Date)

    Public Property PropertyTax As String

    Public Property PropertyTaxDate As Nullable(Of Date)

    Public Property OpenWater As String

    Public Property OpenWaterDate As Nullable(Of Date)

    Public Property ECBTickets As String

    Public Property ECBTicketsDate As Nullable(Of Date)

    Public Property DOBViolation As String

    Public Property DOBViolationDate As Nullable(Of Date)

    Public Property PVB As String

    Public Property PVBDate As Nullable(Of Date)

    Public Property IRSLien As String

    Public Property IRSLienDate As Nullable(Of Date)

    Public Property NYCLien As String

    Public Property NYCLienDate As Nullable(Of Date)

    Public Property FederalLien As String

    Public Property FederalLienDate As Nullable(Of Date)

    Public Property Criminal As String

    Public Property CriminalDate As Nullable(Of Date)

    Public Property Description As String

    Public Property CreateBy As String

    Public Property CreateDate As Nullable(Of Date)

    Public Property BBLE As String


End Class
