'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UnderwritingTrackingView
    Public Property BBLE As String
    Public Property PropertyAddress As String
    Public Property UnderwriteStatus As Nullable(Of Byte)
    Public Property OfferStatus As Nullable(Of Integer)
    Public Property IsShortSaleAccpeted As Integer
    Public Property AcceptedBy As String
    Public Property AcceptedDate As Nullable(Of Date)
    Public Property IsInProcess As Integer
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String

End Class
