'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UnderwritingRequest
    Public Property Id As Integer
    Public Property BBLE As String
    Public Property BriefDescription As String
    Public Property Occupancy As String
    Public Property OccupancyDescription As String
    Public Property IsWorkingOnSS As Nullable(Of Integer)
    Public Property WorkingCompany As String
    Public Property WasHOIFromHO As Nullable(Of Boolean)
    Public Property TotalRequest As Nullable(Of Decimal)
    Public Property UpfrontRequested As Nullable(Of Decimal)
    Public Property WasHOIOffered As Nullable(Of Boolean)
    Public Property TotalOffered As Nullable(Of Decimal)
    Public Property UpfrontOffered As Nullable(Of Decimal)
    Public Property CreateBy As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property UpdateDate As Nullable(Of Date)

End Class
