
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class UserFollowUp

    Public Property FollowUpId As Integer

    Public Property UserName As String

    Public Property FollowUpDate As Nullable(Of Date)

    Public Property BBLE As String

    Public Property Type As Nullable(Of Integer)

    Public Property CaseName As String

    Public Property URL As String

    Public Property Description As String

    Public Property Status As Nullable(Of Integer)

    Public Property UpdateBy As String

    Public Property UpdateTime As Nullable(Of Date)

    Public Property CreateTime As Nullable(Of Date)

    Public Property CreateBy As String


End Class
