'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwUnderwritingProperty
    Public Property ID As Integer
    Public Property BBLE As String
    Public Property UnderwritingStatus As Nullable(Of Integer)
    Public Property UnderwritingCreateBy As String
    Public Property UnderwritingCreateDate As Nullable(Of Date)
    Public Property UnderwritingUpdateDate As Nullable(Of Date)
    Public Property SearchStatus As Nullable(Of Integer)
    Public Property SearchCompletedBy As String
    Public Property SearchCompletedOn As Nullable(Of Date)
    Public Property SearchUpdateDate As Nullable(Of Date)
    Public Property EmployeeName As String
    Public Property NewOfferStatus As Nullable(Of Integer)
    Public Property CaseName As String
    Public Property Team As String

End Class
