'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace CallTrackingService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EmployeeStatisticData", [Namespace]:="http://schemas.datacontract.org/2004/07/CallTracking"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EmployeeStatisticData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AverageField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CallperDealField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CountField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateIntervalField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DealsField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DurationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Duration2Field As System.TimeSpan
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmployeeIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmployeeNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InboundField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InternalField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OutboundField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Average() As Integer
            Get
                Return Me.AverageField
            End Get
            Set
                If (Me.AverageField.Equals(value) <> true) Then
                    Me.AverageField = value
                    Me.RaisePropertyChanged("Average")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CallperDeal() As Double
            Get
                Return Me.CallperDealField
            End Get
            Set
                If (Me.CallperDealField.Equals(value) <> true) Then
                    Me.CallperDealField = value
                    Me.RaisePropertyChanged("CallperDeal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Count() As Integer
            Get
                Return Me.CountField
            End Get
            Set
                If (Me.CountField.Equals(value) <> true) Then
                    Me.CountField = value
                    Me.RaisePropertyChanged("Count")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Data() As String
            Get
                Return Me.DataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DataField, value) <> true) Then
                    Me.DataField = value
                    Me.RaisePropertyChanged("Data")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateInterval() As Date
            Get
                Return Me.DateIntervalField
            End Get
            Set
                If (Me.DateIntervalField.Equals(value) <> true) Then
                    Me.DateIntervalField = value
                    Me.RaisePropertyChanged("DateInterval")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Deals() As Integer
            Get
                Return Me.DealsField
            End Get
            Set
                If (Me.DealsField.Equals(value) <> true) Then
                    Me.DealsField = value
                    Me.RaisePropertyChanged("Deals")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Duration() As String
            Get
                Return Me.DurationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DurationField, value) <> true) Then
                    Me.DurationField = value
                    Me.RaisePropertyChanged("Duration")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Duration2() As System.TimeSpan
            Get
                Return Me.Duration2Field
            End Get
            Set
                If (Me.Duration2Field.Equals(value) <> true) Then
                    Me.Duration2Field = value
                    Me.RaisePropertyChanged("Duration2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmployeeID() As Integer
            Get
                Return Me.EmployeeIDField
            End Get
            Set
                If (Me.EmployeeIDField.Equals(value) <> true) Then
                    Me.EmployeeIDField = value
                    Me.RaisePropertyChanged("EmployeeID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmployeeName() As String
            Get
                Return Me.EmployeeNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmployeeNameField, value) <> true) Then
                    Me.EmployeeNameField = value
                    Me.RaisePropertyChanged("EmployeeName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Inbound() As Integer
            Get
                Return Me.InboundField
            End Get
            Set
                If (Me.InboundField.Equals(value) <> true) Then
                    Me.InboundField = value
                    Me.RaisePropertyChanged("Inbound")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Internal() As Integer
            Get
                Return Me.InternalField
            End Get
            Set
                If (Me.InternalField.Equals(value) <> true) Then
                    Me.InternalField = value
                    Me.RaisePropertyChanged("Internal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property No() As Integer
            Get
                Return Me.NoField
            End Get
            Set
                If (Me.NoField.Equals(value) <> true) Then
                    Me.NoField = value
                    Me.RaisePropertyChanged("No")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Outbound() As Integer
            Get
                Return Me.OutboundField
            End Get
            Set
                If (Me.OutboundField.Equals(value) <> true) Then
                    Me.OutboundField = value
                    Me.RaisePropertyChanged("Outbound")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CallTrackingService.ICallTrackingService")>  _
    Public Interface ICallTrackingService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICallTrackingService/EmployeeReports", ReplyAction:="http://tempuri.org/ICallTrackingService/EmployeeReportsResponse")>  _
        Function EmployeeReports() As CallTrackingService.EmployeeStatisticData()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICallTrackingService/EmployeeStatisticData", ReplyAction:="http://tempuri.org/ICallTrackingService/EmployeeStatisticDataResponse")>  _
        Function EmployeeStatisticData(ByVal emps() As String) As CallTrackingService.EmployeeStatisticData()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICallTrackingServiceChannel
        Inherits CallTrackingService.ICallTrackingService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CallTrackingServiceClient
        Inherits System.ServiceModel.ClientBase(Of CallTrackingService.ICallTrackingService)
        Implements CallTrackingService.ICallTrackingService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function EmployeeReports() As CallTrackingService.EmployeeStatisticData() Implements CallTrackingService.ICallTrackingService.EmployeeReports
            Return MyBase.Channel.EmployeeReports
        End Function
        
        Public Function EmployeeStatisticData(ByVal emps() As String) As CallTrackingService.EmployeeStatisticData() Implements CallTrackingService.ICallTrackingService.EmployeeStatisticData
            Return MyBase.Channel.EmployeeStatisticData(emps)
        End Function
    End Class
End Namespace
