'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConstructionTab
    
    '''<summary>
    '''Common control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Common As Global.IntranetPortal.Common
    
    '''<summary>
    '''ASPxPopupControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl2 As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''ConstructionInitialIntakeTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConstructionInitialIntakeTab As Global.IntranetPortal.ConstructionInitialIntakeTab
    
    '''<summary>
    '''ConstructionPhotosTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConstructionPhotosTab As Global.IntranetPortal.ConstructionPhotosTab
    
    '''<summary>
    '''ConstructionUtilitiesTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConstructionUtilitiesTab As Global.IntranetPortal.ConstructionUtilitiesTab
    
    '''<summary>
    '''ConstructionViolationTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConstructionViolationTab As Global.IntranetPortal.ConstructionViolationTab
    
    '''<summary>
    '''ConstructionProposalBidTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConstructionProposalBidTab As Global.IntranetPortal.ConstructionProposalBidTab
    
    '''<summary>
    '''ConstructionPlansTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConstructionPlansTab As Global.IntranetPortal.ConstructionPlansTab
    
    '''<summary>
    '''ConstructionContractTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConstructionContractTab As Global.IntranetPortal.ConstructionContractTab
    
    '''<summary>
    '''ConstructionSignoffsTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConstructionSignoffsTab As Global.IntranetPortal.ConstructionSignoffsTab
    
    '''<summary>
    '''ConstructionBudgetTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConstructionBudgetTab As Global.IntranetPortal.ConstructionBudgetTab
    
    '''<summary>
    '''ASPxPopupControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl1 As Global.DevExpress.Web.ASPxPopupControl
End Class
