'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AgentCharts

    '''<summary>
    '''callbackDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents callbackDs As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''ASPxCallback1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCallback1 As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''loadAgentCallBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loadAgentCallBack As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''loadAgentZoning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loadAgentZoning As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''loadOfficeLeadsCallback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loadOfficeLeadsCallback As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''char_change_x_axis_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents char_change_x_axis_id As Global.DevExpress.Web.ASPxCallback.ASPxCallback
End Class
