'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class building_0117
    Public Property ogr_fid As Integer
    Public Property ogr_geometry As System.Data.Entity.Spatial.DbGeometry
    Public Property name As String
    Public Property bin As Nullable(Of Decimal)
    Public Property bbl As String
    Public Property cnstrct_yr As Nullable(Of Decimal)
    Public Property lstmoddate As Nullable(Of Date)
    Public Property lststatype As String
    Public Property doitt_id As Nullable(Of Decimal)
    Public Property heightroof As Nullable(Of Decimal)
    Public Property feat_code As Nullable(Of Decimal)
    Public Property groundelev As Nullable(Of Decimal)
    Public Property num_floors As Nullable(Of Decimal)
    Public Property built_code As String
    Public Property shape_area As Nullable(Of Decimal)
    Public Property shape_len As Nullable(Of Decimal)

End Class
