'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CustomReport
    Public Property ReportId As Integer
    Public Property Name As String
    Public Property Description As String
    Public Property Query As String
    Public Property SqlText As String
    Public Property Layout As String
    Public Property Owner As String
    Public Property UpdateTime As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property CreateTime As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property BaseTable As String

End Class
