'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class dtm_0814_tax_lot_polygon
    Public Property ogr_fid As Integer
    Public Property ogr_geometry As System.Data.Entity.Spatial.DbGeometry
    Public Property boro As String
    Public Property block As Nullable(Of Decimal)
    Public Property lot As Nullable(Of Decimal)
    Public Property bbl As String
    Public Property community_ As Nullable(Of Decimal)
    Public Property regular_lo As String
    Public Property number_lot As Nullable(Of Decimal)
    Public Property condo_flag As String
    Public Property reuc_flag As String
    Public Property air_rights As String
    Public Property subterrane As String
    Public Property easement_f As String
    Public Property section_nu As Nullable(Of Decimal)
    Public Property volume_num As Nullable(Of Decimal)
    Public Property page_numbe As String
    Public Property lot_note As String
    Public Property nycmap_bld As Nullable(Of Decimal)
    Public Property missing_rp As Nullable(Of Decimal)
    Public Property conversion As Nullable(Of Decimal)
    Public Property value_refl As Nullable(Of Decimal)
    Public Property created_by As String
    Public Property created_da As Nullable(Of Date)
    Public Property last_modif As String
    Public Property last_mod_1 As Nullable(Of Date)
    Public Property av_change As Nullable(Of Decimal)
    Public Property bw_change As Nullable(Of Decimal)
    Public Property effective_ As String
    Public Property bill_bbl_f As Nullable(Of Decimal)
    Public Property shape_leng As Nullable(Of Decimal)
    Public Property shape_area As Nullable(Of Decimal)

End Class
