'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class dtm_0814_tax_block_polygon
    Public Property ogr_fid As Integer
    Public Property ogr_geometry As System.Data.Entity.Spatial.DbGeometry
    Public Property boro As String
    Public Property block As Nullable(Of Decimal)
    Public Property eop_overla As Nullable(Of Decimal)
    Public Property jagged_st_ As Nullable(Of Decimal)
    Public Property created_by As String
    Public Property created_da As Nullable(Of Date)
    Public Property last_modif As String
    Public Property last_mod_1 As Nullable(Of Date)
    Public Property section_nu As Nullable(Of Decimal)
    Public Property volume_num As Nullable(Of Decimal)
    Public Property shape_leng As Nullable(Of Decimal)
    Public Property shape_area As Nullable(Of Decimal)

End Class
