'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmailMessage
    Public Property EmailId As Integer
    Public Property ToAddress As String
    Public Property CcAddress As String
    Public Property Subject As String
    Public Property Body As String
    Public Property Attachments As String
    Public Property SendDate As Nullable(Of Date)
    Public Property SendBy As String
    Public Property Description As String

End Class
