'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PortalLotInfo
    Public Property BBLE As String
    Public Property boro As String
    Public Property block As Nullable(Of Decimal)
    Public Property lot As Nullable(Of Decimal)
    Public Property bbl As String
    Public Property ogr_geometry As System.Data.Entity.Spatial.DbGeometry
    Public Property LeadsName As String
    Public Property Team As String
    Public Property Color As String
    Public Property ogr_fid As Integer

End Class
