'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WorkingLog
    Public Property LogId As Integer
    Public Property BBLE As String
    Public Property Category As String
    Public Property UserName As String
    Public Property UserId As Integer
    Public Property PageUrl As String
    Public Property StartTime As Nullable(Of Date)
    Public Property EndTime As Nullable(Of Date)
    Public Property Status As Nullable(Of Integer)
    Public Property Description As String
    Public Property ConnectionId As String

End Class
