'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Agent_Properties
    Public Property ID As Integer
    Public Property BBLE As String
    Public Property Agent_Name As String
    Public Property Property_Address As String
    Public Property City As String
    Public Property Zip As String
    Public Property State As String
    Public Property Out_Address As String
    Public Property Out_City As String
    Public Property Out_State As String
    Public Property Out_Zipcode As String
    Public Property Longitude As Nullable(Of Double)
    Public Property Latitude As Nullable(Of Double)
    Public Property Active As Nullable(Of Boolean)

End Class
