'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ApartmentBuilding
    Public Property BuildingId As Integer
    Public Property BBLE As String
    Public Property Address As String
    Public Property Number As String
    Public Property StreetName As String
    Public Property NeighName As String
    Public Property State As String
    Public Property ZipCode As String
    Public Property Borough As String

End Class
