'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class APIOrder
    Public Property ApiOrderID As Integer
    Public Property BBLE As String
    Public Property Acris As Nullable(Of Integer)
    Public Property TaxBill As Nullable(Of Integer)
    Public Property ECBViolation As Nullable(Of Integer)
    Public Property WaterBill As Nullable(Of Integer)
    Public Property Zillow As Nullable(Of Integer)
    Public Property TLO As Nullable(Of Integer)
    Public Property Status As Nullable(Of Integer)
    Public Property OrderTime As Nullable(Of Date)
    Public Property Orderby As String
    Public Property LatestSale As Nullable(Of Integer)

End Class
