'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileAttachment
    Public Property FileID As Integer
    Public Property BBLE As String
    Public Property Name As String
    Public Property ContentType As String
    Public Property Size As Nullable(Of Integer)
    Public Property Data As Byte()
    Public Property Description As String
    Public Property Createby As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property Category As String

End Class
