'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HomeOwnerPhone
    Public Property PhoneID As Integer
    Public Property BBLE As String
    Public Property OwnerName As String
    Public Property Phone As String
    Public Property Type As String
    Public Property Source As Nullable(Of Integer)
    Public Property Description As String
    Public Property _stuats As Integer

    Public ReadOnly Property Stuats As Integer
        Get
            Using Context As New Entities
                Dim con = Context.OwnerContacts.Where(Function(c) c.BBLE = BBLE And Regex.Replace(c.Contact, "[^\d]", "") = Phone).FirstOrDefault
                If (con IsNot Nothing) Then
                    Return con.Status
                End If
            End Using

            Return 100
        End Get
    End Property

End Class
