'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HomeOwner
    Public Property OwnerID As Integer
    Public Property BBLE As String
    Public Property Name As String
    Public Property Address1 As String
    Public Property Address2 As String
    Public Property City As String
    Public Property Country As String
    Public Property State As String
    Public Property Zip As String
    Public Property ExtensionData As String
    Public Property LocateReport As Byte()
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property Active As Nullable(Of Boolean)
    Public Property Description As String
    Public Property UserModified As Nullable(Of Boolean)
    Public Property LastUpdate As Nullable(Of Date)
    Public Property ReportToken As String
    Public Property LocateReportContent As String

End Class
