'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HomeOwnerPhone
    Public Property PhoneID As Integer
    Public Property BBLE As String
    Public Property OwnerName As String
    Public Property Phone As String
    Public Property Type As String
    Public Property Score As Nullable(Of Integer)
    Public Property ListingType As String
    Public Property Source As Nullable(Of Integer)
    Public Property Description As String
    Public Property Comment As String
    Public Property LastCalledDate As Nullable(Of Date)
    Public Property CallCount As Nullable(Of Integer)

End Class
