'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LatLon_View
    Public Property Latitude As Nullable(Of Double)
    Public Property Longitude As Nullable(Of Double)
    Public Property PropertyAddress As String
    Public Property BBLE As String

End Class
