'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LeadsTaxLien
    Public Property TaxLienId As Integer
    Public Property BBLE As String
    Public Property TaxLiensYear As String
    Public Property Amount As Nullable(Of Decimal)
    Public Property Description As String

End Class
