'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LeadsSearchTask
    Public Property Id As Integer
    Public Property TaksName As String
    Public Property SearchFileds As String
    Public Property Status As Nullable(Of Integer)
    Public Property CreateBy As String
    Public Property CreateTime As Nullable(Of Date)
    Public Property DeclineReason As String
    Public Property Type As Nullable(Of Integer)

End Class
