'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LoginLog
    Public Property LogID As Integer
    Public Property Employee As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property LogInTime As Nullable(Of Date)
    Public Property LogoutTime As Nullable(Of Date)
    Public Property IPAddress As String
    Public Property Description As String

End Class
