'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NYC_Scan_TaxLiens_Per_Year
    Public Property BBLE As String
    Public Property Borough As String
    Public Property BoroNum As String
    Public Property Block As String
    Public Property Lot As String
    Public Property Address As String
    Public Property Owner As String
    Public Property LienTotal As Nullable(Of Double)
    Public Property Year As Double

End Class
