'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderRespons
    Public Property ResponseID As Integer
    Public Property BBLE As String
    Public Property APIOrderNo As Nullable(Of Integer)
    Public Property InfoType As String
    Public Property Status As String
    Public Property Updatetime As Nullable(Of Date)

End Class
