'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PortalNote
    Public Property NoteId As Integer
    Public Property Title As String
    Public Property Description As String
    Public Property Createby As String
    Public Property CreateTime As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property UpdateTime As Nullable(Of Date)
    Public Property Status As Nullable(Of Integer)

End Class
