'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PropertyTitle
    Public Property TitleId As Integer
    Public Property CaseId As Integer
    Public Property Type As String
    Public Property CompanyName As String
    Public Property Phone As String
    Public Property ReportOrderDate As Nullable(Of Date)
    Public Property ReceivedDate As Nullable(Of Date)
    Public Property OrderNumber As String
    Public Property CreateBy As String
    Public Property CreateDate As Nullable(Of Date)

End Class
