'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Role
    Public Property Rolename As String
    Public Property ApplicationName As String

    Public Overridable Property UsersInRole As ICollection(Of UsersInRole) = New HashSet(Of UsersInRole)

End Class
