'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SharedLead
    Public Property SharedID As Integer
    Public Property BBLE As String
    Public Property UserName As String
    Public Property Description As String
    Public Property CreateBy As String
    Public Property CreateDate As Date

End Class
