'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Team
    Public Property TeamId As Integer
    Public Property Name As String
    Public Property Manager As String
    Public Property Description As String
    Public Property ParentId As Nullable(Of Integer)
    Public Property Assistant As String
    Public Property OfficeNo As String
    Public Property Address As String

End Class
