'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TLOData
    Public Property OwnerId As Integer
    Public Property BBLE As String
    Public Property ReportToken As String
    Public Property FirstName As String
    Public Property LastName As String
    Public Property SSN As String
    Public Property CreateTime As Nullable(Of Date)
    Public Property Description As String

End Class
