'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserMessage
    Public Property MsgID As Integer
    Public Property UserName As String
    Public Property Title As String
    Public Property Message As String
    Public Property NotifyTime As Nullable(Of Date)
    Public Property Status As Nullable(Of Integer)
    Public Property Createby As String
    Public Property CreateTime As Nullable(Of Date)
    Public Property Description As String
    Public Property ParentMsg As Nullable(Of Integer)
    Public Property ReceiveTime As Nullable(Of Date)
    Public Property BBLE As String

End Class
