'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class RonEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=RonEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ALL_NYC_Tax_Liens_CO_Info() As DbSet(Of ALL_NYC_Tax_Liens_CO_Info)
    Public Overridable Property SearchResluts_View() As DbSet(Of SearchResluts_View)

End Class
