'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SearchResluts_View
    Public Property BBLE As String
    Public Property LeadsName As String
    Public Property MotgCombo As Nullable(Of Decimal)
    Public Property NEIGH_NAME As String
    Public Property ZIP As String
    Public Property [CLASS] As String
    Public Property ORIG_SQFT As Nullable(Of Double)
    Public Property LOT_DIM As String
    Public Property Servicer As String
    Public Property TaxCombo As Nullable(Of Decimal)
    Public Property Type As String
    Public Property ImportDate As Date
    Public Property PropertyAddress As String
    Public Property BLOCK As String
    Public Property LOT As String

End Class
