'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UCTitleSummary

    '''<summary>
    '''LeadsSubMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LeadsSubMenu As Global.IntranetPortal.LeadsSubMenu

    '''<summary>
    '''contentSplitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contentSplitter As Global.DevExpress.Web.ASPxSplitter.ASPxSplitter

    '''<summary>
    '''UrgentGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UrgentGrid As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''gridUpcomingApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridUpcomingApproval As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''CounterOfferGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CounterOfferGrid As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''InvestorReviewGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InvestorReviewGrid As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''DocumentRequestsGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocumentRequestsGrid As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''todayScheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents todayScheduler As Global.DevExpress.Web.ASPxScheduler.ASPxScheduler

    '''<summary>
    '''gridTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTask As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''gridCallback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridCallback As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''AllLeadsGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AllLeadsGrid As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''AllLeadGridViewExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AllLeadGridViewExporter As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter

    '''<summary>
    '''ExportExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportExcel As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ExportPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportPdf As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''notesCallbackPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notesCallbackPanel As Global.DevExpress.Web.ASPxCallbackPanel.ASPxCallbackPanel

    '''<summary>
    '''txtTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTitle As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''txtNotesDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNotesDescription As Global.DevExpress.Web.ASPxEditors.ASPxMemo
End Class
