'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Acris_Master_Owner_View
    Public Property DOCUMENT_ID As String
    Public Property CRFN As String
    Public Property BBLE As String
    Public Property BOROUGH As String
    Public Property BLOCK As String
    Public Property LOT As String
    Public Property PARTIAL_LOT As String
    Public Property DOC__DATE As Nullable(Of Date)
    Public Property RECORDED___FILED As Nullable(Of Date)
    Public Property DOC__TYPE_DESCRIPTION As String
    Public Property DOC__AMOUNT As Nullable(Of Double)
    Public Property REFERENCE_BY_CRFN As String
    Public Property PARTY_TYPE As Short
    Public Property NAME As String

End Class
