'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PenddingAssign_DataLoop_View
    Public Property BBLE As String
    Public Property EmployeeName As String
    Public Property Status As Nullable(Of Integer)
    Public Property Type As Integer
    Public Property CreateDate As Nullable(Of Date)
    Public Property DataLoopStatus As Nullable(Of Integer)
    Public Property DataLoopCreateDate As Nullable(Of Date)
    Public Property LoopType As Nullable(Of Integer)
    Public Property CreateBy As String
    Public Property Acris As Nullable(Of Integer)
    Public Property TaxBill As Nullable(Of Integer)
    Public Property WaterBill As Nullable(Of Integer)
    Public Property Zillow As Nullable(Of Integer)
    Public Property TLO As Nullable(Of Integer)
    Public Property ECBViolation As Nullable(Of Integer)
    Public Property Id As Nullable(Of Integer)
    Public Property NEIGH_NAME As String

End Class
