'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class IntranetPortalEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=IntranetPortalEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property LeadsSoldAfterLPs() As DbSet(Of LeadsSoldAfterLP)
    Public Overridable Property PenddingAssign_DataLoop_View() As DbSet(Of PenddingAssign_DataLoop_View)
    Public Overridable Property PenddingAssign_TLO_view() As DbSet(Of PenddingAssign_TLO_view)
    Public Overridable Property SearchResults() As DbSet(Of SearchResult)

End Class
