'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LeadsList

    '''<summary>
    '''MarkColorCallBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MarkColorCallBack As Global.DevExpress.Web.ASPxCallback

    '''<summary>
    '''lblLeadCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLeadCategory As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''divExpand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divExpand As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gridLeads control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridLeads As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''hfView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfView As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LeadsSubMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LeadsSubMenu As Global.IntranetPortal.LeadsSubMenu

    '''<summary>
    '''ASPxPopupMenu2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupMenu2 As Global.DevExpress.Web.ASPxPopupMenu
End Class
