'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LeadsSubMenu

    '''<summary>
    '''popupMenuLeads control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupMenuLeads As Global.DevExpress.Web.ASPxPopupMenu

    '''<summary>
    '''ASPxPopupMenu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupMenu1 As Global.DevExpress.Web.ASPxPopupMenu

    '''<summary>
    '''ASPxPopupControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl2 As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''popupWinViewFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupWinViewFiles As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''popupViewFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupViewFiles As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''ASPxPopupControl3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl3 As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''PopupContentReAssign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupContentReAssign As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''listboxEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listboxEmployee As Global.DevExpress.Web.ASPxListBox

    '''<summary>
    '''cbArchived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbArchived As Global.DevExpress.Web.ASPxCheckBox

    '''<summary>
    '''btnAssign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAssign As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''reassignCallback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reassignCallback As Global.DevExpress.Web.ASPxCallback

    '''<summary>
    '''ASPxPopupControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl1 As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxPopupControl4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl4 As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''popupContentInProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupContentInProcess As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''hfInProcessBBLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfInProcessBBLE As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lbSelectionMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSelectionMode As Global.DevExpress.Web.ASPxCheckBoxList

    '''<summary>
    '''cbEvictionUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbEvictionUsers As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cbThirdParty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbThirdParty As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPLegalPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPLegalPopup As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxPopupControl5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl5 As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''popupContentDeadLeads control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupContentDeadLeads As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''hfBBLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfBBLE As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cbDeadReasons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDeadReasons As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtDeadLeadDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeadLeadDescription As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''aspxPopupChangeLeadsStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aspxPopupChangeLeadsStatus As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl1 As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''ChangeStatusResonText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChangeStatusResonText As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''aspxPopupShareleads control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aspxPopupShareleads As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''popupRequestUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupRequestUpdate As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''popContentRequestUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popContentRequestUpdate As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''hfRequestUpdateBBLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRequestUpdateBBLE As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''requestUpdateFormlayout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requestUpdateFormlayout As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''txtRequestUpdateLeadsName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequestUpdateLeadsName As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtRequestUpdateCreateby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequestUpdateCreateby As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtRequestUpdateManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequestUpdateManager As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''cbTaskImportant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTaskImportant As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtTaskDes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTaskDes As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''ASPxButton4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton4 As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''leadStatusCallback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents leadStatusCallback As Global.DevExpress.Web.ASPxCallback

    '''<summary>
    '''getAddressCallback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getAddressCallback As Global.DevExpress.Web.ASPxCallback
End Class
