'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Calendar

    '''<summary>
    '''DateNavigator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateNavigator As Global.DevExpress.Web.ASPxScheduler.ASPxDateNavigator

    '''<summary>
    '''calendarPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarPages As Global.DevExpress.Web.ASPxTabControl.ASPxPageControl

    '''<summary>
    '''Scheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Scheduler As Global.DevExpress.Web.ASPxScheduler.ASPxScheduler

    '''<summary>
    '''officeScheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents officeScheduler As Global.DevExpress.Web.ASPxScheduler.ASPxScheduler
End Class
