'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TodoList
    Public Property ListId As Integer
    Public Property Title As String
    Public Property Description As String
    Public Property Category As String
    Public Property Owner As String
    Public Property Comments As String
    Public Property Status As Nullable(Of Integer)
    Public Property DueDate As Nullable(Of Date)
    Public Property UpdateDate As Nullable(Of Date)
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String

End Class
