'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConstructionSpotCheck
    Public Property BBLE As String
    Public Property [date] As Nullable(Of Date)
    Public Property propertyAddress As String
    Public Property access As String
    Public Property numOfWork As Nullable(Of Integer)
    Public Property descInterior As String
    Public Property descExterior As String
    Public Property descMaterial As String
    Public Property isPermitOnsite As Nullable(Of Boolean)
    Public Property permitsAndExpired As String
    Public Property isPlansOnSite As Nullable(Of Boolean)
    Public Property nextDayPlan As String
    Public Property note As String
    Public Property status As Nullable(Of Integer)
    Public Property owner As String
    Public Property Id As Integer

End Class
