'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CorporationEntity
    Public Property EntityId As Integer
    Public Property CorpName As String
    Public Property Address As String
    Public Property PropertyAssigned As String
    Public Property FillingDate As Nullable(Of Date)
    Public Property Signer As String
    Public Property Office As String
    Public Property EIN As String
    Public Property AssignOn As Nullable(Of Date)
    Public Property ReceivedOn As Nullable(Of Date)
    Public Property SubmittedtoAcris As Nullable(Of Boolean)
    Public Property SubmittedOn As Nullable(Of Date)
    Public Property RecordedOn As Nullable(Of Date)
    Public Property Notes As String
    Public Property EINFile As String
    Public Property File2 As String
    Public Property File3 As String
    Public Property CreateBy As String
    Public Property CreateTime As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property UpdateTime As Nullable(Of Date)
    Public Property Status As String
    Public Property OfficeName As String

End Class
