'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TitleTab
    
    '''<summary>
    '''Common control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Common As Global.IntranetPortal.Common
    
    '''<summary>
    '''ASPxPopupControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl2 As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''TitleInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitleInfo As Global.IntranetPortal.TitleInfo
    
    '''<summary>
    '''TitleOwnerLiens control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitleOwnerLiens As Global.IntranetPortal.TitleOwnerLiens
    
    '''<summary>
    '''TitleBuildingLiens control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitleBuildingLiens As Global.IntranetPortal.TitleBuildingLiens
    
    '''<summary>
    '''TitleSurveyAndContin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitleSurveyAndContin As Global.IntranetPortal.TitleSurveyAndContin
    
    '''<summary>
    '''TitlePreclosing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitlePreclosing As Global.IntranetPortal.TitlePreclosing
    
    '''<summary>
    '''TitleFeeClearance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitleFeeClearance As Global.IntranetPortal.TitleFeeClearance
    
    '''<summary>
    '''ASPxPopupControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl1 As Global.DevExpress.Web.ASPxPopupControl
End Class
